[package]
name = "wasm-bindgen-blob-reader"
version = "1.0.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
web-sys = { version = "0.3.77", features = ["File", "Blob", "ReadableStream", "ReadableStreamDefaultReader"] }
