[package]
name = "hf_xet_wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# xet-core deps
chunking = { path = "../chunking" }
merklehash = { path = "../merklehash" }
cas_types = { path = "../cas_types" }
http_client = { path = "../http_client" }
utils = { path = "../utils" }

# wasm deps
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
serde = { version = "1.0.217", features = ["derive"] }
futures = "0.3.31"
log = "0.4.27"
web-sys = { version = "0.3.77", features = ["ReadableStreamDefaultReader", "Blob", "File", "console"] }
async-trait = "0.1.88"
tokio = {version = "1.44.1", features = ["sync"]}
js-sys = "0.3.77"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
