[package]
name = "hf_xet_wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# xet-core deps
chunking = { path = "../chunking" }
merklehash = { path = "../merklehash" }
cas_types = { path = "../cas_types" }

# wasm deps
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
web-sys = "0.3.77"
serde = { version = "1.0.217", features = ["derive"] }

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
