[package]
name = "cas_client"
version = "0.14.5"
edition = "2021"


[dependencies]
cas_object = { path = "../cas_object" }
cas_types = { path = "../cas_types" }
chunk_cache = { path = "../chunk_cache" }
deduplication = { path = "../deduplication" }
error_printer = { path = "../error_printer" }
file_utils = { path = "../file_utils" }
mdb_shard = { path = "../mdb_shard" }
merkledb = { path = "../merkledb" }
merklehash = { path = "../merklehash" }
progress_tracking = { path = "../progress_tracking" }
utils = { path = "../utils" }
xet_threadpool = { path = "../xet_threadpool" }

anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
derivative = { workspace = true }
futures = { workspace = true }
heed = { workspace = true }
http = { workspace = true }
more-asserts = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-retry = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
reqwest-middleware = "0.4"
reqwest-retry = "0.7"


# use embedded webpki root certs for MacOS as native certs take a very long time
# to load, which affects startup time significantly
[target.'cfg(macos)'.dependencies]
reqwest = { version = "0.12", features = [
    "json",
    "stream",
    "rustls-tls-webpki-roots",
] }

[target.'cfg(not(macos))'.dependencies]
reqwest = { version = "0.12", features = ["json", "trust-dns", "stream"] }

# Reqwest -- uses different flags with different features.
[features]
strict = []
default = ["native-ssl"]

# Three options for compliation here. 

# embedded-ssl embeds all ssl stuff in a rust package.  This is the most portable option, but also may not respect local 
# network configurations.  Use this if the native-ssl options don't work.  
embedded-tls = ["reqwest/rustls-tls"]

# Uses native tls in the request package; this uses the native-tls package to wrap openssl, which is a more robust and portable
# way of ensuring that tls just works. 
native-tls = ["reqwest/native-tls"]

# This uses the above, but statically compiles in openssl, which makes the result more portable at the expense of 
# library size. 
native-tls-vendored = ["reqwest/native-tls-vendored"]


[dev-dependencies]
httpmock = { workspace = true }
rand = { workspace = true }
tracing-test = { workspace = true }
wiremock = { workspace = true }
