[package]
name = "git_xet"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "git-xet"
path = "src/bin/main.rs"

[dependencies]
data = { path = "../data" }
cas_client = { path = "../cas_client" }
progress_tracking = { path = "../progress_tracking" }
utils = { path = "../utils" }

anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
git-url-parse = { workspace = true }
git2 = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

signal-hook = "0.3"
signal-hook-tokio = { version = "0.3", features = ["futures-v0_3"] }

