name: Test huggingface_hub xet tests

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  hub-python-tests:
    runs-on: ubuntu-latest
    steps:
      # checkout out xet-core
      - uses: actions/checkout@v4 
      # checkout out huggingface_hub
      - uses: actions/checkout@v4
        with:
          repository: huggingface/huggingface_hub
          path: huggingface_hub
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Create venv
        run: python3 -m venv .venv
      - name: Build wheel
        uses: PyO3/maturin-action@v1
        with:
          command: develop
          sccache: 'true'
          working-directory: hf_xet
      - name: Install huggingface_hub dependencies
        run: |
          source .venv/bin/activate
          python3 -m pip install -e 'huggingface_hub[testing]'
      - name: Install gdb
        run: sudo apt-get update && sudo apt-get install -y gdb
      - name: Run huggingface_hub xet tests
        run: |
          source .venv/bin/activate
          set -eux
          export RUST_BACKTRACE=1
          export RUST_LIB_BACKTRACE=1
          export PYTHONFAULTHANDLER=1

          gdb -batch -ex "run" -ex "bt" --args $(which python) -m pytest huggingface_hub/tests/test_xet_*.py
          gdb -batch -ex "run" -ex "bt" --args $(which python) -m pytest huggingface_hub/tests/test_xet_*.py
          gdb -batch -ex "run" -ex "bt" --args $(which python) -m pytest huggingface_hub/tests/test_xet_*.py
          gdb -batch -ex "run" -ex "bt" --args $(which python) -m pytest huggingface_hub/tests/test_xet_*.py
          gdb -batch -ex "run" -ex "bt" --args $(which python) -m pytest huggingface_hub/tests/test_xet_*.py
          gdb -batch -ex "run" -ex "bt" --args $(which python) -m pytest huggingface_hub/tests/test_xet_*.py
          gdb -batch -ex "run" -ex "bt" --args $(which python) -m pytest huggingface_hub/tests/test_xet_*.py